# Trigger the workflow manually
name: Manual simple app dispatch
on: 
  workflow_dispatch:

jobs:
  invoke_app:
      uses: cesiztel/reusable-workflow/.github/workflows/simple_app.yml@main
      secrets: inherit