# Trigger the workflow manually
name: Manual simple app dispatch
on: 
  workflow_dispatch:

jobs:
  invoke_app:
      uses: cesiztel/reusable-workflow/.github/workflows/simple-app.yml@main
      with:
        # Indicate we triggered the app manually
        TRIGGER: manual_${{ github.run_id }}.${{ github.run_number }}
      secrets: inherit